### ISSUE TITLE
404 cardanodocs.translations

### ISSUE THREAD

**Issue by EvertonMelo** [CardanodocTranslations/cardanodocs.translations#1]
this url  https://cardanodocstranslations.github.io/cardanodocs.translations returno error 404

**Comment by marcusvinicg** [comment]
Same issue here.

**Comment by gufmar** [comment]
Good to see you here. where did you become aware of this fork?
We didn't continue the efforts as we heard that official site at the moment will not accept pull requests. We're still waiting for further details from official side regarding workflow and collaboration for the announced new website and his professional translations. Then we see if and how the community could contribute with additional languages

**Comment by EvertonMelo** [comment]
@gufmar 
wait, 

I'm only will reported "error" 
the link: https://cardanodocstranslations.github.io/cardanodocs.translations

it is on the main page: 

" CardanodocTranslations/cardanodocs.translations" 
Language translations of Cardano Settlement Layer Documentation https://cardanodocstranslation

I just reported the broken link.
if you can correct it, I can close the issue.

**Comment by gufmar** [comment]
ok I removed the link to github pages

**Comment by EvertonMelo** [comment]
Thank you.
